# Generated by Django 4.1.1 on 2022-09-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='jobs_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primer trabajo'),
        ),
        migrations.AddField(
            model_name='project',
            name='jobs_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Segundo trabajo'),
        ),
        migrations.AddField(
            model_name='project',
            name='jobs_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tercer trabajo'),
        ),
        migrations.AddField(
            model_name='project',
            name='jobs_4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cuarto trabajo'),
        ),
        migrations.AddField(
            model_name='project',
            name='jobs_5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Quinto trabajo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección web'),
        ),
    ]
