# Generated by Django 4.1.1 on 2022-09-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jobs_1',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Primer trabajo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jobs_2',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Segundo trabajo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jobs_3',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Tercer trabajo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jobs_4',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Cuarto trabajo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='jobs_5',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Quinto trabajo'),
        ),
    ]
